### ISSUE TITLE
❓ [question]: Publish a new release

### ISSUE THREAD

**Issue by kumy** [raven-actions/debug#16]
### ✅ Checklist

- [X] I've searched the project's [`issues`](https://github.com/raven-actions/debug/issues?q=is%3Aissue) and did not find answer for my question.

### ❓ Question

Hi @DariuszPorowski 

Quoting from one of my workflow annotations
> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/github-script@v6. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

I tracked the message to be apparently coming from your great action :)

It seems the needed fix has already been merged [on Nov 14, 2023](https://github.com/raven-actions/debug/pull/11#event-10948204019) with PR #11 
From what I can see from the [Publish Release workflow runs](https://github.com/raven-actions/debug/actions/workflows/release.yml), latest [release v1.0.2](https://github.com/raven-actions/debug/releases/tag/v1.0.2) was triggered/published [on May 8, 2023](https://github.com/raven-actions/debug/actions/runs/4918632057)

Could you please trigger/publish a new release? :pray: 

Thanks!

### 📜 Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by DariuszPorowski** [comment]
@kumy Thanks for letting me know! :) done - `v1.1.0` released :)

**Comment by kumy** [comment]
No more warning in my workflow runs, perfect! Thanks :+1:
